### PR TITLE
public some function

### PR DESCRIPTION
**Pull request by quininer**
Sometimes we need to repeatedly squeezing a sponge, like [newhope/poly.rs](https://github.com/quininer/newhope/blob/master/src/poly.rs#L90).

:D

### CODE REVIEW

**Comment by debris** [comment]
I agree with making `absorb/pad/squeeze` pub, but imo `finalize` should remain unchanged. For convenience you can also add `keccakf` method to Keccak impl

```rust
impl Keccak {
/*
some code
*/

  #[inline]
  pub fn keccakf(&mut self) {
    keccakf(&mut self.a);
  }

/*
some code
*/
}
```

**Comment by debris** [comment]
Thank you! I will release new version in few minutes! :)

**Comment by quininer** [comment]
Thank you! :D

**Comment by debris** [comment]
`1.1.0` released

**Pull request merged**
